### PR TITLE
Phpcs

### PR DESCRIPTION
**Pull request by fezfez**
Add a clear and clean code style.

## important 

- The code is checked by ./vendor/bin/phpcs
- The code can be fixed automaticly by ./vendor/bin/phpcbf

All code change are made by ./vendor/bin/phpcbf

### CODE REVIEW

**Comment by guillaume-sainthillier** [comment]
I used to use https://github.com/FriendsOfPHP/PHP-CS-Fixer but if you prefer https://github.com/squizlabs/PHP_CodeSniffer we can switch.

If so could you delete the /.php_cs.dist and ensure PHP same header will be added to every files with PHPCS?

**Comment by fezfez** [comment]
> I used to use https://github.com/FriendsOfPHP/PHP-CS-Fixer but if you prefer https://github.com/squizlabs/PHP_CodeSniffer we can switch.
> 
> If so could you delete the /.php_cs.dist and ensure that same header will be added to every files with PHPCS?

done

**Comment by guillaume-sainthillier** [comment]
Thanks but I don't see any rules in the PHPCS config file which force the same header on every files 😄

**Comment by fezfez** [comment]
I didn't find similar rule with phpcs...

Possible solution is to make pr to add this rule or keep phpcs fixer with this only rule. What do you think?

**Comment by guillaume-sainthillier** [comment]
I think we could keep PHPCSFixer and add the missing rules :
1. declare_strict_types (adds strict_type)
2. use native functions
3. etc

Will check this and add workflow for an auto apply of these rules :-)

**Pull request closed without merging**
