### PR TITLE
Move ci to laminas-continuous-integration

### PR DESCRIPTION
**Pull request by fezfez**
This way CI is more consistent and it automatically tests on right PHP version

### CODE REVIEW

**Comment by guillaume-sainthillier** [comment]
Hello Stéphane, thanks for your work.
Just a few questions:

1. What's the benefits of renaming yaml to yml files?
2. Why bumping dev packages minor versions?

**Comment by fezfez** [comment]
hi @guillaume-sainthillier 

"Why bumping dev packages minor versions?" => In php 8.1 some devs deps are failing, only the last version is working
"What's the benefits of renaming yaml to yml files?" => My bad i revert

**Comment by guillaume-sainthillier** [comment]
Ok nice. Please use yaml format for .github/workflows/continuous-integration.yml and I will merge 👍

**Comment by fezfez** [comment]
done ;)

**Pull request merged**
